### ISSUE TITLE
Conditional Dependencies?

### ISSUE THREAD

**Issue by sheepman4267** [getsolus/eopkg#114]
Thinking out loud here. How hard would it be to implement conditional dependencies in eopkg? This would also require changes to build tooling, but could be super useful for kernel module packages. I'm not promising to build it, but this issue can serve as a center for discussion around the feasibility of this idea. 

Initial idea for `package.yml` syntax:

```yaml
rundeps:  # traditional rundeps
  - package1
  - package2
conditional-rundeps:
  linux-lts:  # if this package is installed...
    - my-lts-counterpart  # ...then depend on these packages.
    - my-other-lts-dependency
  linux-current:  # elif this package is installed...
    - my-current-counterpart  # ...then depend on these instead.
    - my-other-current-dependency
```

Knowing how long the project has been around, I doubt this is the first go-round for the idea, and it's probably prohibitively complicated. I still intend to look into it when I have spare time. Please comment your thoughts!
